---
package:
  package_tool: apt
  action: install
  package_name: apache2
  notify: apache2, delayed
file:
  location: apache.conf
  content_file: contentfile
  owner: ubuntu
  group: ubuntu
  mode: '740'
  notify: apache2, delayed
