---
package:
  package_tool: apt
  action: remove
  package_name: apache2
  notify: apache2, delayed
file:
  location: apache.conf
  content_file: contentfile
  owner: root
  group: root
  mode: '777'
  notify: apache2, delayed
