---
package-1:
  package_tool: apt
  action: install
  package_name: php5
package-2:
  package_tool: apt
  action: install
  package_name: libapache2-mod-php5
package-2:
  package_tool: apt
  action: install
  package_name: apache2
  notify: apache2, delayed
file-1:
  location: /var/www/html/index.php 
  content_file: contentfile
  owner: root
  group: root
  mode: '774'
  notify: apache2, delayed
file-2:
  location: /etc/apache2/mods-available/dir.conf
  content_file: default_dir.conf 
  owner: root
  group: root
  mode: '774'
  notify: apache2, delayed
