---
package:
  package_tool: apt
  action: remove
  package_name: apache2
  notify: apache2, delayed
file:
  location: somefile
  content: "somecontent <sthis> <thisn> and that "
  content_file: contentfile
  owner: root
  group: root
  mode: '777'
  notify: apache2, delayed
